// Next
import { GetStaticPropsContext } from 'next';
import Head from 'next/head';

// Components
import { Layout } from 'components/layout';

const NotFound = () => {
  const handleBack = () => {
    window.history.back();
  };

  return (
    <>
      <Head>
        <title>WORKDB - Not Found</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1>Esta pagina não existe</h1>
        <button onClick={handleBack} aria-label="back">
          <h1>voltar</h1>
        </button>
      </Layout>
    </>
  );
};

export default NotFound;

export async function getStaticProps({ locale }: GetStaticPropsContext) {
  return {
    props: {
      messages: (await import(`../i18n/locales/${locale}.json`)).default,
    },
  };
}
