// Next
import { NextPage } from 'next';
import { GetStaticPropsContext } from 'next';
import Head from 'next/head';

// Components
import { Layout } from 'components/layout';

const Solutions: NextPage = () => {
  return (
    <>
      <Head>
        <title>WORKDB - Soluções</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout selectedKey="2">
        <h1>Soluções</h1>
      </Layout>
    </>
  );
};

export default Solutions;

export async function getStaticProps({ locale }: GetStaticPropsContext) {
  return {
    props: {
      messages: (await import(`../../i18n/locales/${locale}.json`)).default,
    },
  };
}
